// GENERATED by scripts/seo/merge-enrichment.ts — do not edit by hand.
// data/seo/faqs/shared-faqs.ts — global + housing-profile FAQ pools (brief §6.3).
import type { FAQ } from '../types';

export const GLOBAL_FAQS: FAQ[] = [
  {
    "id": "faq-global-1",
    "q": "What does MyBuddyMaid do?",
    "a": "MyBuddyMaid connects households with verified domestic helpers: full-time and part-time maids, cooks, babysitters and nannies, elder-care attendants and all-rounder domestic help. You share your requirements, matching helpers are shortlisted, and you interview and trial before confirming. The service is available in Delhi NCR, Mumbai, Pune, Bangalore and Mangalore.",
    "scope": "global",
    "tags": [
      "global"
    ]
  },
  {
    "id": "faq-global-2",
    "q": "How do I book a helper?",
    "a": "You can reach out on WhatsApp, call the helpline, or book through the app. Share the service you need, your locality, preferred timings and any specific requirements such as language or cuisine. Matching profiles are then shortlisted and interviews or a trial are arranged with you.",
    "scope": "global",
    "tags": [
      "global"
    ]
  },
  {
    "id": "faq-global-3",
    "q": "Are the helpers verified?",
    "a": "Yes. Every helper's documents are checked and background verification is completed before they are placed with a household. Helper details are kept on record, and you can ask about a profile's verification status before the interview.",
    "scope": "global",
    "tags": [
      "global"
    ]
  },
  {
    "id": "faq-global-4",
    "q": "What if the helper leaves or does not work out?",
    "a": "A replacement policy is in place across all services. If a helper leaves, is irregular, or the fit is not right, you can raise a replacement request and a new profile is matched to your original requirements. The specific terms are shared with you at the time of booking.",
    "scope": "global",
    "tags": [
      "global"
    ]
  }
];

export const HOUSING_FAQ_POOLS: Record<string, FAQ[]> = {
  "gated-societies": [
    {
      "id": "faq-housing-gated-societies-1",
      "q": "Do helpers need a gate pass to enter my society?",
      "a": "Most gated societies require domestic helpers to be registered with the society office or security and issued a gate pass or ID card before regular entry. The household usually applies for this with the helper's ID and photograph. It is best to start the registration as soon as the helper is confirmed so the first working day is not delayed.",
      "scope": "housing",
      "tags": [
        "gated-societies"
      ]
    },
    {
      "id": "faq-housing-gated-societies-2",
      "q": "Does my society's visitor app affect helper entry?",
      "a": "Many societies use a visitor-management app where residents approve helper entry or add the helper as a regular daily visitor. Once added, the helper can check in at the gate each day without a fresh approval. Ask your society office how new helpers are added, since the process differs from society to society.",
      "scope": "housing",
      "tags": [
        "gated-societies"
      ]
    },
    {
      "id": "faq-housing-gated-societies-3",
      "q": "Are there timing restrictions for helpers in gated societies?",
      "a": "Some societies set entry and exit windows for domestic helpers or ask that helpers use a designated gate or service lift. Check your society's rules before agreeing a slot so the helper's timing fits within them. Helper verification records can be shared with the society office if it asks for them.",
      "scope": "housing",
      "tags": [
        "gated-societies"
      ]
    },
    {
      "id": "faq-housing-gated-societies-4",
      "q": "Can a helper work in several flats in the same society?",
      "a": "Yes, and it is common. Part-time helpers often serve multiple homes within one society, which makes scheduling easier for both the helper and residents. If you are looking for a part-time slot, a helper already registered in your society can usually start sooner because the gate formalities are already done.",
      "scope": "housing",
      "tags": [
        "gated-societies"
      ]
    }
  ],
  "independent-houses": [
    {
      "id": "faq-housing-independent-houses-1",
      "q": "Are helper timings more flexible in independent houses?",
      "a": "Generally yes. Without society gate rules or visitor apps, households in independent houses can agree timings directly with the helper, including early morning or late evening slots. It is still a good idea to fix a slot so the helper can plan their other homes around it.",
      "scope": "housing",
      "tags": [
        "independent-houses"
      ]
    },
    {
      "id": "faq-housing-independent-houses-2",
      "q": "Do helpers need any registration for independent houses?",
      "a": "There is no society office to register with, but many residents' welfare associations and local police stations encourage or require domestic-helper verification. Helpers placed through MyBuddyMaid are already document-checked and background-verified, and you can keep a copy of the helper's ID for your own records.",
      "scope": "housing",
      "tags": [
        "independent-houses"
      ]
    },
    {
      "id": "faq-housing-independent-houses-3",
      "q": "Is a larger house a problem for a part-time helper?",
      "a": "Independent houses often have more floors, a courtyard or terrace, and outdoor areas than a flat, so the task list can be longer. Be clear about which areas are to be covered daily and which are occasional, and size the slot accordingly. A full-time helper or domestic help may suit larger homes better than a short part-time slot.",
      "scope": "housing",
      "tags": [
        "independent-houses"
      ]
    },
    {
      "id": "faq-housing-independent-houses-4",
      "q": "Can a live-in helper stay in an independent house?",
      "a": "Yes. Independent houses often have a servant's room or a separate space, which makes live-in arrangements for maids, cooks, nannies or elder-care attendants straightforward. The household provides sleeping space, meals and agreed rest time, and informs the local association or neighbours as a courtesy where that is the norm.",
      "scope": "housing",
      "tags": [
        "independent-houses"
      ]
    }
  ],
  "mixed": [
    {
      "id": "faq-housing-mixed-1",
      "q": "My area has both flats and independent houses. Does that change how helpers are placed?",
      "a": "In mixed neighbourhoods the entry process depends on your building: apartment complexes may need a gate pass or visitor-app registration, while independent houses and small buildings usually do not. Let us know which type you live in when booking so the helper is briefed on any entry formalities in advance.",
      "scope": "housing",
      "tags": [
        "mixed"
      ]
    },
    {
      "id": "faq-housing-mixed-2",
      "q": "Are helpers easy to find in mixed residential areas?",
      "a": "Mixed areas usually have a steady pool of part-time helpers who move between nearby flats and houses through the day, since the homes are close together. Timing flexibility on your side helps, as helpers plan their route around the slots they already serve.",
      "scope": "housing",
      "tags": [
        "mixed"
      ]
    },
    {
      "id": "faq-housing-mixed-3",
      "q": "Do timings differ between flats and houses in the same area?",
      "a": "They can. Societies may set entry windows for helpers, whereas independent houses can agree any slot directly. If you live in a society, check its helper rules before fixing a slot; if you live in a house, you have more freedom to choose early or late timings.",
      "scope": "housing",
      "tags": [
        "mixed"
      ]
    },
    {
      "id": "faq-housing-mixed-4",
      "q": "What should I tell the helper about reaching my home?",
      "a": "In mixed areas, addresses can be harder to locate than in a single large society. Share a clear landmark, the building or house name, floor, and whether there is a lift, and mention any gate or security step. This helps the helper arrive on time on the first day.",
      "scope": "housing",
      "tags": [
        "mixed"
      ]
    }
  ],
  "builder-floors": [
    {
      "id": "faq-housing-builder-floors-1",
      "q": "Do builder floors have any entry formalities for helpers?",
      "a": "Most builder-floor buildings do not have a society office or visitor app, so there is usually no gate pass to arrange. Entry is agreed directly between the household and the helper, sometimes with a shared building gate or a guard. Some residents' welfare associations still ask for helper details, which the helper's verification record can support.",
      "scope": "housing",
      "tags": [
        "builder-floors"
      ]
    },
    {
      "id": "faq-housing-builder-floors-2",
      "q": "Is stair access an issue for helpers on upper builder floors?",
      "a": "Many builder floors have no lift, so helpers climb stairs to upper floors, and this is worth mentioning when booking. It matters most for tasks like carrying laundry or groceries and for elder-care attendants who may accompany a senior downstairs. Mention the floor number and whether a lift exists so the helper knows what to expect.",
      "scope": "housing",
      "tags": [
        "builder-floors"
      ]
    },
    {
      "id": "faq-housing-builder-floors-3",
      "q": "How do helpers reach builder-floor lanes without parking or wide roads?",
      "a": "Builder-floor colonies are typically laid out in narrow lanes that helpers reach on foot, by cycle, or by auto and bus to the nearest main road. Sharing the lane or block number and a nearby landmark helps, since house numbering in these colonies can be confusing on a first visit.",
      "scope": "housing",
      "tags": [
        "builder-floors"
      ]
    },
    {
      "id": "faq-housing-builder-floors-4",
      "q": "Can one helper work across several floors in the same building?",
      "a": "Yes, and it is common in builder-floor buildings where each floor is a separate household. A part-time helper serving more than one floor can often take on another slot in the same building, which shortens the wait for a new placement. Ask neighbours whether their helper has a free slot, or mention this when booking.",
      "scope": "housing",
      "tags": [
        "builder-floors"
      ]
    }
  ]
};
