/**
 * Generate cities.json programmatically
 * Run: node seo-generator/build-cities.js
 */
const fs = require('fs');
const path = require('path');

// ══════ CITY DATA ══════
const citiesRaw = [
  // ── TIER 1 ──
  { slug:"delhi", name:"Delhi", state:"Delhi", stateSlug:"delhi", tier:1, pop:"32 million", lat:28.6139, lng:77.2090, geo:"IN-DL",
    ctx:"As India's capital and one of the world's largest metropolitan areas, Delhi has enormous demand for domestic help. From sprawling bungalows in South Delhi to modern high-rises in Dwarka, millions of families depend on professional home help.",
    lifestyle:"Delhi's extreme summers exceeding 45°C and harsh winters make household management physically demanding, increasing the need for reliable domestic support year-round.",
    why:"With both parents working in most Delhi households and the city's notorious traffic making commutes exhaustingly long, professional home help isn't a luxury — it's a daily necessity for millions of families.",
    nearby:["gurugram","noida","ghaziabad","faridabad"],
    localities:["South Delhi","Dwarka","Rohini","Vasant Kunj","Greater Kailash","Saket","Lajpat Nagar","Hauz Khas","Defence Colony","Malviya Nagar","Rajouri Garden","Janakpuri","Pitampura","Paschim Vihar","East Delhi","Mayur Vihar","Vasant Vihar","Green Park","Nehru Place","Kalkaji"],
    salaryMult:1.0 },
  { slug:"mumbai", name:"Mumbai", state:"Maharashtra", stateSlug:"maharashtra", tier:1, pop:"21 million", lat:19.0760, lng:72.8777, geo:"IN-MH",
    ctx:"Mumbai, India's financial capital, has the highest cost of living and correspondingly the strongest demand for domestic help. From sea-facing apartments in Bandra to high-rises in Powai, every household needs reliable support.",
    lifestyle:"Mumbai's relentless work culture, long train commutes averaging 90 minutes each way, and compact living spaces make professional home help essential for maintaining quality of life.",
    why:"In a city where the average commute takes 90 minutes each way and both partners work demanding corporate jobs, having a reliable maid or cook at home is the only way to maintain work-life balance.",
    nearby:["thane","navi-mumbai","pune"],
    localities:["Andheri","Bandra","Powai","Goregaon","Malad","Borivali","Kandivali","Juhu","Worli","Lower Parel","Dadar","Chembur","Mulund","Vikhroli","Ghatkopar","Vashi","Kharghar","Mira Road","Thane West","Colaba"],
    salaryMult:1.05 },
  { slug:"bangalore", name:"Bangalore", state:"Karnataka", stateSlug:"karnataka", tier:1, pop:"13 million", lat:12.9716, lng:77.5946, geo:"IN-KA",
    ctx:"Bangalore, India's Silicon Valley, is home to millions of IT professionals and startup founders. The city's tech-driven, dual-income households create massive demand for verified domestic help.",
    lifestyle:"With both partners typically working in IT companies with demanding schedules, Bangalore families rely heavily on domestic help for cooking, cleaning, and childcare.",
    why:"The tech boom has made Bangalore one of India's most expensive cities to live in. Young couples moving here from other states have no local support network, making professional maid and cook services essential.",
    nearby:["mysore","chennai","hyderabad"],
    localities:["Whitefield","HSR Layout","Koramangala","Indiranagar","Electronic City","Marathahalli","JP Nagar","Jayanagar","Hebbal","Yelahanka","Banashankari","BTM Layout","Sarjapur Road","Bellandur","Malleshwaram","Rajajinagar","Basavanagudi","KR Puram","Hennur","Bannerghatta Road"],
    salaryMult:1.0 },
  { slug:"hyderabad", name:"Hyderabad", state:"Telangana", stateSlug:"telangana", tier:1, pop:"10 million", lat:17.3850, lng:78.4867, geo:"IN-TG",
    ctx:"Hyderabad's booming IT corridor along HITEC City and Gachibowli has attracted millions of working professionals, driving strong demand for reliable domestic help across the city.",
    lifestyle:"The city's expanding tech parks and pharmaceutical industry mean more dual-income families who need professional support to manage their households efficiently.",
    why:"Hyderabad's rapid IT-driven growth has brought thousands of families from across India, most without extended family support. Professional domestic help bridges this gap perfectly.",
    nearby:["bangalore","chennai","vijayawada"],
    localities:["Gachibowli","HITEC City","Banjara Hills","Jubilee Hills","Madhapur","Kondapur","Kukatpally","Secunderabad","Begumpet","Ameerpet","LB Nagar","Miyapur","Manikonda","Uppal","Dilsukhnagar","Kompally","Shamshabad","Attapur","Nallagandla","Mokila"],
    salaryMult:0.9 },
  { slug:"chennai", name:"Chennai", state:"Tamil Nadu", stateSlug:"tamil-nadu", tier:1, pop:"11 million", lat:13.0827, lng:80.2707, geo:"IN-TN",
    ctx:"Chennai, the gateway to South India, combines traditional family values with a modern IT-driven economy. The city's automobile and tech industries support millions of working families who need domestic help.",
    lifestyle:"Chennai's hot, humid climate and the demands of its thriving IT corridor in OMR and Sholinganallur make household management particularly challenging without domestic support.",
    why:"With the city's IT parks stretching along OMR and the traditional business districts in T. Nagar and Anna Nagar, Chennai families across all income brackets depend on domestic help for daily household operations.",
    nearby:["bangalore","coimbatore","madurai"],
    localities:["Anna Nagar","T Nagar","Adyar","Velachery","OMR","Sholinganallur","Porur","Tambaram","Chromepet","Guindy","Nungambakkam","Mylapore","Besant Nagar","Thiruvanmiyur","Perungudi","Medavakkam","Pallavaram","Ambattur","Avadi","ECR"],
    salaryMult:0.88 },
  { slug:"pune", name:"Pune", state:"Maharashtra", stateSlug:"maharashtra", tier:1, pop:"7.4 million", lat:18.5204, lng:73.8567, geo:"IN-MH",
    ctx:"Pune, Maharashtra's cultural capital and a major IT hub, attracts young professionals and families from across India. The city's pleasant climate and growing infrastructure make it one of the fastest-growing markets for domestic help.",
    lifestyle:"With Hinjewadi's massive IT parks and a thriving startup ecosystem, Pune's dual-income households increasingly rely on professional domestic help to manage their homes.",
    why:"Pune's transformation from a quiet retirement city to a bustling IT hub means thousands of young families who have moved from other states and need reliable, verified domestic help without local connections.",
    nearby:["mumbai","nashik","nagpur"],
    localities:["Kothrud","Hinjewadi","Wakad","Baner","Viman Nagar","Kalyani Nagar","Hadapsar","Magarpatta","Aundh","Koregaon Park","Pimpri-Chinchwad","Bavdhan","Pashan","Shivaji Nagar","Kharadi","Undri","NIBM","Warje","Kondhwa","Sinhagad Road"],
    salaryMult:0.85 },
  { slug:"kolkata", name:"Kolkata", state:"West Bengal", stateSlug:"west-bengal", tier:1, pop:"15 million", lat:22.5726, lng:88.3639, geo:"IN-WB",
    ctx:"Kolkata, the cultural capital of India, maintains strong traditions of domestic help going back generations. The city's unique combination of old-world charm and modern IT growth creates steady demand for household professionals.",
    lifestyle:"Kolkata families traditionally value home-cooked Bengali cuisine and immaculate households, making skilled cooks and experienced maids highly sought after throughout the year.",
    why:"With the IT sector growing in Salt Lake and New Town and traditional businesses thriving in Park Street and Ballygunge, Kolkata families across economic segments need trustworthy domestic professionals.",
    nearby:["siliguri","durgapur","asansol"],
    localities:["Salt Lake","New Town","Park Street","Ballygunge","Alipore","Behala","Garia","Jadavpur","Lake Town","Dum Dum","Howrah","Tollygunge","Jodhpur Park","Kasba","Rajarhat","EM Bypass","Kaikhali","Baranagar","Sealdah","Ultadanga"],
    salaryMult:0.78 },
  { slug:"ahmedabad", name:"Ahmedabad", state:"Gujarat", stateSlug:"gujarat", tier:1, pop:"8.6 million", lat:23.0225, lng:72.5714, geo:"IN-GJ",
    ctx:"Ahmedabad, Gujarat's commercial capital and India's first UNESCO World Heritage City, has a vibrant business community. The city's textile, pharmaceutical, and diamond industries support millions of families who value quality domestic help.",
    lifestyle:"Gujarati families place enormous importance on home-cooked meals and a clean, well-maintained household — making skilled cooks and reliable maids essential in Ahmedabad's culture.",
    why:"With the city expanding rapidly along the SG Highway corridor and Ahmedabad's business-oriented culture keeping families busy, professional domestic help has become indispensable for maintaining the Gujarati standard of hospitality.",
    nearby:["vadodara","surat","gandhinagar","rajkot"],
    localities:["SG Highway","Prahlad Nagar","Satellite","Bopal","Bodakdev","Vastrapur","Navrangpura","Paldi","Maninagar","Chandkheda","Thaltej","Gota","South Bopal","Ambawadi","Jodhpur Village","Naranpura","Shahibaug","Ellis Bridge","Motera","Isanpur"],
    salaryMult:0.82 },
  { slug:"gurugram", name:"Gurugram", state:"Haryana", stateSlug:"haryana", tier:1, pop:"3.2 million", lat:28.4595, lng:77.0266, geo:"IN-HR",
    ctx:"Gurugram (Gurgaon), the millennium city, is India's corporate headquarters hub with offices of Fortune 500 companies. The city's high-income expat and corporate population creates premium demand for domestic help.",
    lifestyle:"With some of India's highest per-capita income and sprawling luxury condominiums, Gurugram families expect premium, well-trained domestic professionals who can manage upscale households.",
    why:"Gurugram's corporate workforce — including expats, C-suite executives, and dual-income IT professionals — needs reliable, English-speaking, well-groomed domestic staff that local agencies often cannot provide.",
    nearby:["delhi","faridabad","noida"],
    localities:["DLF Phase 1-5","Golf Course Road","Sohna Road","Sector 49","Sector 56-57","MG Road","Nirvana Country","South City","Palam Vihar","Sector 82-84","Udyog Vihar","Manesar","Sector 45-48","Golf Course Extension","Dwarka Expressway","Sector 67-70","Sector 15","Sushant Lok","Malibu Town","Vatika City"],
    salaryMult:0.98 },
  { slug:"noida", name:"Noida", state:"Uttar Pradesh", stateSlug:"uttar-pradesh", tier:1, pop:"3.5 million", lat:28.5355, lng:77.3910, geo:"IN-UP",
    ctx:"Noida and Greater Noida, part of the Delhi NCR region, are major IT and corporate hubs with modern townships and high-rise living. The city's young, professional population drives strong demand for domestic help.",
    lifestyle:"Noida's modern apartment complexes and gated societies house thousands of young families who have relocated from other states, creating a huge market for verified domestic professionals.",
    why:"As a satellite city with minimal traditional domestic help networks, Noida residents face acute difficulty finding trustworthy maids and cooks — making professional placement services like MyBuddyMaid invaluable.",
    nearby:["delhi","ghaziabad","gurugram","faridabad"],
    localities:["Sector 62","Sector 50","Sector 137","Sector 75-76","Sector 44","Sector 18","Sector 78","Greater Noida West","Sector 93-96","Sector 120-122","Sector 128-134","Jaypee Greens","Gaur City","Pari Chowk","Sector 150","Sector 100","Sector 32","Expressway","Amity Area","Sector 37"],
    salaryMult:0.92 },
  { slug:"ghaziabad", name:"Ghaziabad", state:"Uttar Pradesh", stateSlug:"uttar-pradesh", tier:1, pop:"2.4 million", lat:28.6692, lng:77.4538, geo:"IN-UP",
    ctx:"Ghaziabad, known as the 'Gateway of UP', is a fast-growing Delhi NCR city with modern residential complexes and an expanding commercial sector. It offers more affordable living than Delhi while being well-connected via metro.",
    lifestyle:"Ghaziabad's growing number of gated societies and modern apartments houses young families who commute to Delhi and Noida for work, creating strong demand for domestic help.",
    why:"Families in Ghaziabad work long hours with Delhi commutes and need dependable domestic help. The city's lack of organized placement agencies makes MyBuddyMaid's verified service especially valuable here.",
    nearby:["delhi","noida","meerut"],
    localities:["Indirapuram","Vaishali","Kaushambi","Raj Nagar Extension","Crossing Republik","Vasundhara","Shalimar Garden","Lal Kuan","Govindpuram","Sahibabad","Wave City","NH-24","Ahinsa Khand","Niti Khand","Gaur City Gate","Shakti Khand"],
    salaryMult:0.85 },
  { slug:"faridabad", name:"Faridabad", state:"Haryana", stateSlug:"haryana", tier:1, pop:"1.9 million", lat:28.4089, lng:77.3178, geo:"IN-HR",
    ctx:"Faridabad, Haryana's largest city and part of the Delhi NCR, is a growing industrial and residential hub. The city's improving infrastructure and metro connectivity are attracting more families who need domestic support.",
    lifestyle:"As Faridabad transitions from an industrial town to a modern residential city, families in newer sectors and townships increasingly seek professional, verified domestic help.",
    why:"Faridabad's proximity to Delhi means many residents commute daily for work, spending hours in transit. Reliable domestic help ensures their homes are well-maintained despite their demanding schedules.",
    nearby:["delhi","gurugram","noida"],
    localities:["Sector 15-21","Greater Faridabad","Neharpar","Sector 81-89","NIT Faridabad","Ballabgarh","Surajkund","Sector 37","BPTP","Crown Interiorz","Mewla Maharajpur","Sector 28-30"],
    salaryMult:0.82 },

  // ── TIER 2 ──
  { slug:"jaipur", name:"Jaipur", state:"Rajasthan", stateSlug:"rajasthan", tier:2, pop:"4 million", lat:26.9124, lng:75.7873, geo:"IN-RJ",
    ctx:"Jaipur, the Pink City and Rajasthan's capital, blends royal heritage with modern growth. The city's tourism, IT, and gem industries support a growing middle class that values well-maintained homes.",
    lifestyle:"Rajasthani families traditionally maintain elaborate households with high standards of cleanliness and hospitality, making professional domestic help a cultural norm.",
    why:"With Jaipur's IT sector growing in Mahindra SEZ and Sitapura, more dual-income families are moving to the city and need reliable domestic help without local contacts.",
    nearby:["delhi","ajmer","udaipur","jodhpur"],
    localities:["Vaishali Nagar","Malviya Nagar","Mansarovar","C-Scheme","Tonk Road","Jagatpura","Pratap Nagar","Raja Park","Sodala","Civil Lines","Bani Park","Vidhyadhar Nagar"],
    salaryMult:0.72 },
  { slug:"lucknow", name:"Lucknow", state:"Uttar Pradesh", stateSlug:"uttar-pradesh", tier:2, pop:"3.6 million", lat:26.8467, lng:80.9462, geo:"IN-UP",
    ctx:"Lucknow, the City of Nawabs and UP's capital, is known for its rich culture and tehzeeb. The city's growing IT sector and government institutions create steady demand for domestic professionals.",
    lifestyle:"Lucknow's culture of refined hospitality and elaborate home-cooked Awadhi cuisine makes skilled cooks and well-mannered maids particularly valued by local families.",
    why:"As Lucknow modernizes rapidly with new IT parks and metro infrastructure, working families need professional domestic help that matches the city's high standards of household management.",
    nearby:["kanpur","agra","varanasi"],
    localities:["Gomti Nagar","Hazratganj","Aliganj","Indira Nagar","Mahanagar","Alambagh","Vikas Nagar","Jankipuram","Chinhat","Aashiyana"],
    salaryMult:0.68 },
  { slug:"chandigarh", name:"Chandigarh", state:"Punjab", stateSlug:"punjab", tier:2, pop:"1.2 million", lat:30.7333, lng:76.7794, geo:"IN-CH",
    ctx:"Chandigarh, India's best-planned city, consistently ranks among the highest per-capita income cities. The city's affluent residents and modern lifestyle create strong demand for quality domestic help.",
    lifestyle:"With its well-planned sectors, green spaces, and high standard of living, Chandigarh families expect organized, professional domestic help that matches the city's modern ethos.",
    why:"Chandigarh's affluent population — including senior government officials, business families, and professionals — expects premium domestic staff but struggles with limited organized placement options.",
    nearby:["ludhiana","ambala","patiala"],
    localities:["Sector 17","Sector 22","Sector 35","Sector 43","Sector 44","Manimajra","Mohali","Panchkula","Zirakpur","IT Park","Sector 8-11","Sector 15"],
    salaryMult:0.75 },
  { slug:"indore", name:"Indore", state:"Madhya Pradesh", stateSlug:"madhya-pradesh", tier:2, pop:"3.2 million", lat:22.7196, lng:75.8577, geo:"IN-MP",
    ctx:"Indore, India's cleanest city for multiple consecutive years, is Madhya Pradesh's commercial capital. The city's growing IT industry and business-friendly environment attract families from across central India.",
    lifestyle:"Indore's reputation as India's cleanest city means residents take household cleanliness seriously, creating strong demand for meticulous, well-trained domestic help.",
    why:"With Indore's Super Corridor developing into a major IT hub, young professionals relocating here need professional domestic help in a city where organized placement services are still limited.",
    nearby:["bhopal","ujjain"],
    localities:["Vijay Nagar","Palasia","AB Road","Super Corridor","Scheme 78","Nipania","Rau","Bhawarkua","South Tukoganj","Sapna Sangeeta"],
    salaryMult:0.65 },
  { slug:"surat", name:"Surat", state:"Gujarat", stateSlug:"gujarat", tier:2, pop:"7.5 million", lat:21.1702, lng:72.8311, geo:"IN-GJ",
    ctx:"Surat, the diamond and textile capital of India, is one of the fastest-growing cities in the world. The city's wealthy business community and expanding middle class drive strong demand for domestic professionals.",
    lifestyle:"Surat's Gujarati business families value fresh, home-cooked meals and spotless homes, making experienced cooks and reliable maids indispensable for daily household operations.",
    why:"With the city's booming diamond polishing and textile industries keeping families busy around the clock, professional domestic help is essential for maintaining the quality of life Surat residents expect.",
    nearby:["ahmedabad","vadodara"],
    localities:["Vesu","Adajan","Piplod","Pal","Athwa","City Light","Althan","Katargam","Dumas Road","Varachha"],
    salaryMult:0.7 },
  { slug:"nagpur", name:"Nagpur", state:"Maharashtra", stateSlug:"maharashtra", tier:2, pop:"2.9 million", lat:21.1458, lng:79.0882, geo:"IN-MH",
    ctx:"Nagpur, the orange city and geographical center of India, is emerging as a logistics and IT hub. MIHAN SEZ and growing infrastructure are bringing new families to the city who need domestic support.",
    lifestyle:"Nagpur's scorching summers make household chores physically exhausting, driving families to rely on domestic help year-round, especially for cooking and cleaning.",
    why:"With MIHAN SEZ attracting IT companies and Nagpur's growing role as a logistics hub, working families increasingly need organized domestic help services that traditional brokers cannot reliably provide.",
    nearby:["pune","indore","raipur"],
    localities:["Dharampeth","Civil Lines","Sadar","Manish Nagar","Wardhaman Nagar","Khamla","Pratap Nagar","Hingna","Wadi","Seminary Hills"],
    salaryMult:0.65 },
  { slug:"thane", name:"Thane", state:"Maharashtra", stateSlug:"maharashtra", tier:2, pop:"2.4 million", lat:19.2183, lng:72.9781, geo:"IN-MH",
    ctx:"Thane, the city of lakes, is a thriving satellite city of Mumbai offering better living spaces at relatively affordable prices. Its growing population of young professionals creates strong demand for domestic help.",
    lifestyle:"Thane residents enjoy a more spacious lifestyle than Mumbai but share the same demanding work schedules, making domestic help essential for managing larger apartments and family homes.",
    why:"Many Thane residents commute to Mumbai daily, spending 2-3 hours in transit. Having a dependable maid and cook waiting at home is not just convenient — it's necessary for a functional household.",
    nearby:["mumbai","navi-mumbai","nashik"],
    localities:["Ghodbunder Road","Hiranandani Estate","Majiwada","Manpada","Pokhran Road","Kolshet","Vartak Nagar","Naupada","Wagle Estate","Balkum"],
    salaryMult:0.8 },
  { slug:"navi-mumbai", name:"Navi Mumbai", state:"Maharashtra", stateSlug:"maharashtra", tier:2, pop:"2 million", lat:19.0330, lng:73.0297, geo:"IN-MH",
    ctx:"Navi Mumbai, the planned satellite city across the harbour from Mumbai, is one of India's most well-organized urban areas. With the upcoming international airport, the city is poised for massive growth.",
    lifestyle:"Navi Mumbai's modern townships and IT parks in Airoli and Mahape house thousands of young professionals who need reliable domestic support to manage their busy lives.",
    why:"As a planned city with residents primarily from other states, Navi Mumbai lacks the informal domestic help networks found in older cities. Professional placement services fill this critical gap.",
    nearby:["mumbai","thane","pune"],
    localities:["Vashi","Kharghar","Nerul","Airoli","Belapur","Panvel","Seawoods","Kopar Khairane","Sanpada","Kamothe"],
    salaryMult:0.8 },
  { slug:"vadodara", name:"Vadodara", state:"Gujarat", stateSlug:"gujarat", tier:2, pop:"2.1 million", lat:22.3072, lng:73.1812, geo:"IN-GJ",
    ctx:"Vadodara (Baroda), the cultural capital of Gujarat, combines industrial strength with a rich heritage. The city's mix of traditional Gujarati families and modern professionals creates diverse domestic help needs.",
    lifestyle:"Vadodara's strong cultural identity means families value traditional cooking skills and household management, making experienced, culturally-aware domestic help particularly prized.",
    why:"With major industrial companies like L&T and ONGC bringing professionals from across India, Vadodara has a growing segment of nuclear families without local support who need professional domestic help.",
    nearby:["ahmedabad","surat"],
    localities:["Alkapuri","Gotri","Manjalpur","Waghodia Road","Sama","Akota","Vasna","Harni","Fatehgunj","Race Course"],
    salaryMult:0.65 },
  { slug:"coimbatore", name:"Coimbatore", state:"Tamil Nadu", stateSlug:"tamil-nadu", tier:2, pop:"2.1 million", lat:11.0168, lng:76.9558, geo:"IN-TN",
    ctx:"Coimbatore, the Manchester of South India, is a major textile and engineering hub. The city's growing IT sector in Tidel Park and ELCOT SEZ is diversifying its economy and domestic help demand.",
    lifestyle:"Coimbatore's blend of industrial wealth and traditional Tamil values means families expect both modern efficiency and cultural sensitivity from their domestic professionals.",
    why:"With Coimbatore's economy expanding beyond textiles into IT and manufacturing, young dual-income families are increasingly seeking professional, verified domestic help they can trust.",
    nearby:["chennai","kochi","madurai"],
    localities:["RS Puram","Gandhipuram","Peelamedu","Saravanampatti","Singanallur","Ganapathy","Race Course","Vadavalli","Thudiyalur","Kovaipudur"],
    salaryMult:0.62 },
  { slug:"kochi", name:"Kochi", state:"Kerala", stateSlug:"kerala", tier:2, pop:"2.1 million", lat:9.9312, lng:76.2673, geo:"IN-KL",
    ctx:"Kochi, Kerala's commercial capital and a major port city, has a thriving IT sector in Infopark and SmartCity. The city's cosmopolitan population includes NRIs and Gulf-returned families with high domestic help expectations.",
    lifestyle:"Kerala's high literacy rate and exposure to global standards mean Kochi families expect educated, well-mannered domestic professionals — not just basic household help.",
    why:"With many Kochi families having members working in Gulf countries and IT firms, the demand is for premium, trustworthy domestic help that can manage upscale households independently.",
    nearby:["thiruvananthapuram","coimbatore"],
    localities:["Edappally","Kakkanad","Palarivattom","Vyttila","Aluva","Kaloor","Ernakulam","Fort Kochi","Tripunithura","Marine Drive"],
    salaryMult:0.65 },
  { slug:"bhopal", name:"Bhopal", state:"Madhya Pradesh", stateSlug:"madhya-pradesh", tier:2, pop:"2.4 million", lat:23.2599, lng:77.4126, geo:"IN-MP",
    ctx:"Bhopal, the City of Lakes and Madhya Pradesh's capital, is a growing administrative and educational hub. The city's government sector and expanding IT presence create steady demand for domestic professionals.",
    lifestyle:"Bhopal's unique blend of Nawabi culture and modern governance makes it a city where households value both traditional cooking skills and efficient, reliable household management.",
    why:"As the state capital with a large population of government employees and a growing IT sector, Bhopal families need dependable domestic help but have limited organized placement options.",
    nearby:["indore","jabalpur"],
    localities:["Arera Colony","MP Nagar","Shahpura","Kolar Road","Hoshangabad Road","BHEL","Habibganj","TT Nagar","Bairagarh","Mandideep"],
    salaryMult:0.62 },
  { slug:"visakhapatnam", name:"Visakhapatnam", state:"Andhra Pradesh", stateSlug:"andhra-pradesh", tier:2, pop:"2.1 million", lat:17.6868, lng:83.2185, geo:"IN-AP",
    ctx:"Visakhapatnam (Vizag), Andhra Pradesh's largest city, is a major port and industrial hub. The city's steel plant, naval base, IT parks, and pharma companies support a large working population needing domestic help.",
    lifestyle:"Vizag's combination of industrial workers, navy personnel, and IT professionals creates diverse demand for domestic help ranging from basic cleaning to specialized cooking.",
    why:"With AP's executive capital functions and growing IT industry, Vizag is attracting professionals from across India who need verified domestic help in an unfamiliar city.",
    nearby:["vijayawada","hyderabad"],
    localities:["MVP Colony","Seethammadhara","Gajuwaka","Madhurawada","Rushikonda","Dwaraka Nagar","Waltair","Pendurthi","NAD Junction","Gopalapatnam"],
    salaryMult:0.6 },
  { slug:"mysore", name:"Mysore", state:"Karnataka", stateSlug:"karnataka", tier:2, pop:"1.2 million", lat:12.2958, lng:76.6394, geo:"IN-KA",
    ctx:"Mysore (Mysuru), the City of Palaces, combines royal heritage with a growing IT presence. Infosys's largest campus is here, bringing tech professionals who need modern domestic help services.",
    lifestyle:"Mysore's reputation for cleanliness and cultural refinement means families expect domestic help that maintains the city's high standards of order and hospitality.",
    why:"With Infosys and Wipro operations bringing thousands of professionals, Mysore's domestic help market is growing rapidly but lacks the organized placement infrastructure found in Bangalore.",
    nearby:["bangalore","coimbatore"],
    localities:["Vijayanagar","Gokulam","Kuvempunagar","JP Nagar","Hebbal","Saraswathipuram","Jayalakshmipuram","Bogadi","Dattagalli","Hootagalli"],
    salaryMult:0.6 },
  { slug:"ludhiana", name:"Ludhiana", state:"Punjab", stateSlug:"punjab", tier:2, pop:"2 million", lat:30.9010, lng:75.8573, geo:"IN-PB",
    ctx:"Ludhiana, Punjab's largest industrial city, is the hosiery and cycle capital of India. The city's wealthy business families and growing middle class value premium household management.",
    lifestyle:"Punjabi families are known for generous hospitality and elaborate home-cooked meals, making skilled cooks who can prepare authentic Punjabi cuisine highly valued in Ludhiana.",
    why:"Ludhiana's business families juggle demanding factory schedules and social commitments, creating strong demand for reliable domestic staff who can manage large Punjabi households efficiently.",
    nearby:["chandigarh","jalandhar","amritsar","patiala"],
    localities:["Model Town","Sarabha Nagar","BRS Nagar","Civil Lines","Dugri","Pakhowal Road","Ferozepur Road","Rajguru Nagar","Haibowal","Jamalpur"],
    salaryMult:0.62 },
  { slug:"dehradun", name:"Dehradun", state:"Uttarakhand", stateSlug:"uttarakhand", tier:2, pop:"0.8 million", lat:30.3165, lng:78.0322, geo:"IN-UK",
    ctx:"Dehradun, Uttarakhand's capital, is known for its elite boarding schools, defence establishments, and pleasant climate. Retired defence personnel and affluent school communities create niche demand for quality domestic help.",
    lifestyle:"Dehradun's pleasant year-round climate and growing popularity as a retirement and education destination mean households often need long-term, live-in domestic professionals.",
    why:"With ONGC headquarters, IMA, and multiple boarding schools, Dehradun has a significant population of senior officials and NRI families who need premium, verified domestic help.",
    nearby:["haridwar","chandigarh"],
    localities:["Rajpur Road","Clement Town","Mussoorie Road","Race Course","Dalanwala","Ballupur","Jakhan","GMS Road","Nehru Colony","Vasant Vihar"],
    salaryMult:0.6 },
  { slug:"bhubaneswar", name:"Bhubaneswar", state:"Odisha", stateSlug:"odisha", tier:2, pop:"1.1 million", lat:20.2961, lng:85.8245, geo:"IN-OD",
    ctx:"Bhubaneswar, Odisha's smart city capital, is rapidly developing with new IT parks, AIIMS, and improved infrastructure. The city's professional population is growing and creating demand for organized domestic help.",
    lifestyle:"Bhubaneswar's mix of government employees, IT professionals, and traditional Odia families creates diverse needs for domestic help — from specialized cooking to comprehensive household management.",
    why:"As Odisha's capital modernizes rapidly, professional families are increasingly seeking verified domestic help rather than relying on informal neighborhood referrals.",
    nearby:["cuttack","rourkela"],
    localities:["Saheed Nagar","Jaydev Vihar","Patia","Chandrasekharpur","Khandagiri","Nayapalli","Bapuji Nagar","Unit 1-9","Mancheswar","Infocity"],
    salaryMult:0.58 },
  { slug:"ranchi", name:"Ranchi", state:"Jharkhand", stateSlug:"jharkhand", tier:2, pop:"1.5 million", lat:23.3441, lng:85.3096, geo:"IN-JH",
    ctx:"Ranchi, Jharkhand's capital, is a growing administrative and industrial city. The presence of major PSUs like HEC and the state government creates a stable demand for domestic professionals.",
    lifestyle:"Ranchi's pleasant hilltop climate and expanding urban areas attract government and corporate employees who need reliable domestic help for their households.",
    why:"With limited organized domestic placement services in Jharkhand, Ranchi families often struggle to find verified, trustworthy household help — making MyBuddyMaid's service especially valuable.",
    nearby:["jamshedpur","dhanbad","patna"],
    localities:["Doranda","Harmu","Lalpur","Kanke","Bariatu","Ashok Nagar","Morabadi","Kadru","Hinoo","Ratu Road"],
    salaryMult:0.55 },
  { slug:"agra", name:"Agra", state:"Uttar Pradesh", stateSlug:"uttar-pradesh", tier:2, pop:"2.2 million", lat:27.1767, lng:78.0081, geo:"IN-UP",
    ctx:"Agra, home to the Taj Mahal, is one of India's most visited cities. Beyond tourism, the city's leather and footwear industry supports a busy commercial population needing domestic help.",
    lifestyle:"Agra's business families, running leather exports and shoe manufacturing units, maintain traditional North Indian households that require experienced domestic staff.",
    why:"With Agra's tourist economy and manufacturing sector keeping families busy, there's growing demand for verified domestic help that the city's informal placement market cannot reliably provide.",
    nearby:["delhi","mathura","lucknow"],
    localities:["Kamla Nagar","Sikandra","Tajganj","Civil Lines","Dayal Bagh","Shahganj","Fatehabad Road","MG Road","Raja Mandi","Khandari"],
    salaryMult:0.58 },
  { slug:"varanasi", name:"Varanasi", state:"Uttar Pradesh", stateSlug:"uttar-pradesh", tier:2, pop:"1.8 million", lat:25.3176, lng:82.9739, geo:"IN-UP",
    ctx:"Varanasi, one of the world's oldest living cities and a major spiritual center, blends ancient traditions with modern development. PM Modi's constituency has seen significant infrastructure upgrades.",
    lifestyle:"Varanasi's deeply spiritual culture means households often need domestic help who understand and respect religious practices, dietary restrictions, and the rhythms of a sacred city.",
    why:"With BHU's academic community, growing tourism infrastructure, and the city's modernization under Smart City initiatives, Varanasi's working families increasingly need organized domestic help.",
    nearby:["lucknow","patna","allahabad"],
    localities:["Lanka","Sigra","Bhelupur","Mahmoorganj","Sarnath","Cantt Area","Shivpur","DLW","Kabir Chaura","Pandeypur"],
    salaryMult:0.55 },
  { slug:"kanpur", name:"Kanpur", state:"Uttar Pradesh", stateSlug:"uttar-pradesh", tier:2, pop:"3.1 million", lat:26.4499, lng:80.3319, geo:"IN-UP",
    ctx:"Kanpur, UP's industrial powerhouse, is known for its leather and textile industries. The city's IIT campus and large industrial population create steady demand for domestic professionals.",
    lifestyle:"Kanpur's industrial families and IIT academic community represent two distinct segments that both need reliable domestic help but face limited organized options.",
    why:"Despite being one of UP's largest cities, Kanpur has very few organized domestic placement agencies, making families dependent on unreliable informal networks for household help.",
    nearby:["lucknow","agra","allahabad"],
    localities:["Civil Lines","Kakadeo","Swaroop Nagar","Kidwai Nagar","Rawatpur","Govind Nagar","Kalyanpur","Shyam Nagar","Harsh Nagar","Jajmau"],
    salaryMult:0.55 },
  { slug:"nashik", name:"Nashik", state:"Maharashtra", stateSlug:"maharashtra", tier:2, pop:"1.8 million", lat:19.9975, lng:73.7898, geo:"IN-MH",
    ctx:"Nashik, the wine capital of India, is a fast-growing city with strong industrial and agricultural sectors. The city's pleasant climate attracts retirees and professionals from Mumbai and Pune.",
    lifestyle:"Nashik's reputation as a liveable city with lower costs than Mumbai means many families relocating here expect quality domestic help at competitive rates.",
    why:"As Mumbai and Pune professionals increasingly move to Nashik for better quality of life, they bring expectations for organized domestic help that the local market is still developing to meet.",
    nearby:["mumbai","pune","nagpur"],
    localities:["College Road","Gangapur Road","Nashik Road","Panchavati","Satpur","Deolali","CIDCO","Pathardi","Indira Nagar","Makhmalabad"],
    salaryMult:0.6 },
  { slug:"raipur", name:"Raipur", state:"Chhattisgarh", stateSlug:"chhattisgarh", tier:2, pop:"1.2 million", lat:21.2514, lng:81.6296, geo:"IN-CT",
    ctx:"Raipur, Chhattisgarh's capital, is a rapidly developing smart city with growing IT and steel industries. The city's expanding middle class is creating new demand for organized domestic help services.",
    lifestyle:"As Raipur modernizes with new malls, IT parks, and residential townships, families are transitioning from informal domestic help arrangements to professional, verified placements.",
    why:"Raipur's growth as a state capital and industrial hub is bringing professionals from other states who need reliable domestic help but find very few organized options in the city.",
    nearby:["nagpur","bhopal"],
    localities:["Shankar Nagar","Devendra Nagar","Civil Lines","Telibandha","Fafadih","VIP Road","Tatibandh","Amanaka","Mowa","Daldal Seoni"],
    salaryMult:0.55 },
  { slug:"guwahati", name:"Guwahati", state:"Assam", stateSlug:"assam", tier:2, pop:"1.1 million", lat:26.1445, lng:91.7362, geo:"IN-AS",
    ctx:"Guwahati, the gateway to Northeast India, is the region's largest city and commercial hub. The city's growing service sector and government presence create demand for organized domestic help.",
    lifestyle:"Guwahati's unique Northeast Indian culture and cuisine mean families often need domestic help who understand local food traditions including fish preparation, bamboo shoot cooking, and Assamese thali preparation.",
    why:"As Guwahati grows into a major Northeast hub with new IIT, AIIMS, and IT parks, professional families are seeking organized domestic help beyond traditional word-of-mouth hiring.",
    nearby:["siliguri"],
    localities:["GS Road","Zoo Road","Chandmari","Paltan Bazaar","Dispur","Beltola","Hatigaon","Ganeshguri","Basistha","Kahilipara"],
    salaryMult:0.55 },
  { slug:"patna", name:"Patna", state:"Bihar", stateSlug:"bihar", tier:2, pop:"2.5 million", lat:25.6093, lng:85.1376, geo:"IN-BR",
    ctx:"Patna, Bihar's capital and one of the world's oldest continuously inhabited cities, is undergoing rapid modernization. New flyovers, malls, and residential complexes are transforming the city's domestic help landscape.",
    lifestyle:"Patna families value traditional home-cooked Bihar and Eastern UP cuisine, making skilled cooks who can prepare litti-chokha, sattu paratha, and other regional specialties highly sought after.",
    why:"Despite being a state capital with a large government workforce, Patna has minimal organized domestic placement services, leaving families to struggle with unreliable informal arrangements.",
    nearby:["varanasi","ranchi","lucknow"],
    localities:["Boring Road","Kankarbagh","Patliputra Colony","Bailey Road","Rajendra Nagar","Fraser Road","Danapur","Saguna More","Anisabad","Mahendru"],
    salaryMult:0.52 },
  { slug:"madurai", name:"Madurai", state:"Tamil Nadu", stateSlug:"tamil-nadu", tier:2, pop:"1.5 million", lat:9.9252, lng:78.1198, geo:"IN-TN",
    ctx:"Madurai, the temple city and cultural capital of Tamil Nadu, is one of the oldest continuously inhabited cities in the world. The city's educational institutions and growing IT sector drive domestic help demand.",
    lifestyle:"Madurai families maintain strong Tamil traditions with elaborate home-cooked South Indian meals and meticulous household management, requiring experienced, culturally-aware domestic professionals.",
    why:"With multiple engineering colleges, AIIMS, and growing commercial activities, Madurai's working families need organized domestic help that respects their cultural values and food traditions.",
    nearby:["coimbatore","chennai"],
    localities:["Anna Nagar","KK Nagar","SS Colony","Thirunagar","Villapuram","Mattuthavani","Palanganatham","Teppakulam","Tallakulam","Arapalayam"],
    salaryMult:0.52 },
  { slug:"jodhpur", name:"Jodhpur", state:"Rajasthan", stateSlug:"rajasthan", tier:2, pop:"1.5 million", lat:26.2389, lng:73.0243, geo:"IN-RJ",
    ctx:"Jodhpur, the Blue City and Rajasthan's second-largest city, is a major military and tourism hub. AIIMS Jodhpur and the air force base create pockets of professionals needing domestic help.",
    lifestyle:"Jodhpur's extreme desert climate with temperatures touching 50°C makes indoor household work exhausting, driving strong demand for domestic helpers throughout the summer months.",
    why:"With military families frequently transferring in and out of Jodhpur and the city's growing healthcare and education sectors, there's consistent demand for reliable, pre-verified domestic professionals.",
    nearby:["jaipur","udaipur"],
    localities:["Ratanada","Shastri Nagar","Pal Road","Chopasni Housing Board","Sardarpura","Mandore Road","Kamla Nehru Nagar","Paota","Basni","Circuit House Area"],
    salaryMult:0.52 },
  { slug:"vijayawada", name:"Vijayawada", state:"Andhra Pradesh", stateSlug:"andhra-pradesh", tier:2, pop:"1.5 million", lat:16.5062, lng:80.6480, geo:"IN-AP",
    ctx:"Vijayawada, the business capital of Andhra Pradesh, is witnessing rapid growth as Amaravati develops as the new state capital. The city's commercial activity and construction boom are driving domestic help demand.",
    lifestyle:"Vijayawada's bustling commercial culture keeps families busy with business and trade, making reliable domestic help essential for maintaining their Telugu-style households.",
    why:"With Amaravati capital development bringing government officials and construction workers, and Vijayawada's own commercial growth, the demand for organized domestic help services is surging.",
    nearby:["hyderabad","visakhapatnam"],
    localities:["Benz Circle","Governorpet","Moghalrajpuram","Poranki","Gannavaram","Kanuru","Tadepalli","Mangalagiri","Gunadala","Auto Nagar"],
    salaryMult:0.52 },
  { slug:"thiruvananthapuram", name:"Thiruvananthapuram", state:"Kerala", stateSlug:"kerala", tier:2, pop:"1.7 million", lat:8.5241, lng:76.9366, geo:"IN-KL",
    ctx:"Thiruvananthapuram, Kerala's capital, is home to the state secretariat, Technopark (India's first IT park), and ISRO. The city's educated, Gulf-returned population has high expectations for domestic help quality.",
    lifestyle:"Kerala's near-100% literacy and high exposure to global standards mean Thiruvananthapuram families expect articulate, well-trained domestic professionals — not just basic household help.",
    why:"With a large population of Gulf-returned families and Technopark IT professionals, Thiruvananthapuram needs professional domestic help that matches the city's sophisticated lifestyle expectations.",
    nearby:["kochi","coimbatore"],
    localities:["Technopark","Kazhakkoottam","Kowdiar","Pattom","Vazhuthacaud","Thycaud","Sasthamangalam","Kesavadasapuram","Vellayambalam","Medical College"],
    salaryMult:0.6 },
  { slug:"mangalore", name:"Mangalore", state:"Karnataka", stateSlug:"karnataka", tier:2, pop:"0.7 million", lat:12.9141, lng:74.8560, geo:"IN-KA",
    ctx:"Mangalore (Mangaluru), a major port city in Karnataka, has a thriving banking, education, and petrochemical sector. The city's cosmopolitan mix of Tulu, Konkani, and Kannada-speaking families creates diverse domestic help needs.",
    lifestyle:"Mangalore's unique food culture combining Tulu Bunt cuisine, Konkani dishes, and Udupi cooking makes it a city where good cooks are especially valued and hard to find.",
    why:"With multiple engineering colleges, MRPL refinery, and a growing IT sector, Mangalore's professional population needs organized domestic help that understands the region's distinct cultural nuances.",
    nearby:["bangalore","mysore","kochi"],
    localities:["Kadri","Hampankatta","Bejai","Falnir","Kankanady","Derebail","Kottara","Bendoorwell","Attavar","Surathkal"],
    salaryMult:0.58 }
];

// ══════ SALARY TEMPLATES ══════
const baseSalaries = {
  "maid-service":           { pt:[8000,14000], ft:[12000,18000], li:[15000,25000] },
  "full-time-maid-service": { pt:[12000,18000], ft:[15000,22000], li:[18000,28000] },
  "cook-service":           { pt:[10000,15000], ft:[14000,20000], li:[16000,25000] },
  "nanny-service":          { pt:[12000,18000], ft:[15000,22000], li:[18000,28000] },
  "elderly-care-service":   { pt:[14000,20000], ft:[18000,25000], li:[20000,35000] },
  "postnatal-care-service": { pt:[15000,22000], ft:[20000,30000], li:[25000,40000] }
};

function fmt(n) {
  return '₹' + Math.round(n/1000)*1000 > 0 ? '₹' + (Math.round(n/1000)*1000).toLocaleString('en-IN') : '₹' + n.toLocaleString('en-IN');
}

function buildSalaries(mult) {
  const result = {};
  for (const [svc, ranges] of Object.entries(baseSalaries)) {
    result[svc] = {
      partTime: `${fmt(Math.round(ranges.pt[0]*mult))} – ${fmt(Math.round(ranges.pt[1]*mult))}`,
      fullTime: `${fmt(Math.round(ranges.ft[0]*mult))} – ${fmt(Math.round(ranges.ft[1]*mult))}`,
      liveIn:   `${fmt(Math.round(ranges.li[0]*mult))} – ${fmt(Math.round(ranges.li[1]*mult))}`
    };
  }
  return result;
}

function slugify(name) {
  return name.toLowerCase()
    .replace(/[()]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

// ══════ BUILD CITIES ══════
const cities = citiesRaw.map(c => {
  const localities = (c.localities || []).map(name => ({
    slug: slugify(name),
    name: name,
    context: `${name} is a well-known residential area in ${c.name}, ${c.state}. Families here seek verified domestic help for their apartments and independent houses. MyBuddyMaid provides trusted, police-verified professionals in ${name} with 24-hour deployment.`
  }));

  return {
    slug: c.slug,
    name: c.name,
    state: c.state,
    stateSlug: c.stateSlug,
    tier: c.tier,
    population: c.pop,
    lat: c.lat,
    lng: c.lng,
    geoRegion: c.geo,
    context: c.ctx,
    lifestyleNote: c.lifestyle,
    whyFamiliesNeedHelp: c.why,
    salaries: buildSalaries(c.salaryMult),
    localities: localities,
    nearbyCities: c.nearby,
    localFAQs: [
      {
        q: `How much does a maid cost in ${c.name}?`,
        a: `Part-time maid salaries in ${c.name} typically range from ${buildSalaries(c.salaryMult)['maid-service'].partTime} per month for 2-4 hours of daily work. Full-time maids cost ${buildSalaries(c.salaryMult)['maid-service'].fullTime} per month. Rates vary based on the specific area, experience, and scope of duties.`
      },
      {
        q: `Which areas in ${c.name} does MyBuddyMaid serve?`,
        a: `MyBuddyMaid provides verified domestic help across all major areas of ${c.name} including ${localities.slice(0,5).map(l=>l.name).join(', ')}${localities.length > 5 ? ', and more' : ''}. We deploy professionals within 24 hours of booking.`
      }
    ]
  };
});

// ══════ WRITE FILE ══════
const outPath = path.join(__dirname, 'data', 'cities.json');
fs.writeFileSync(outPath, JSON.stringify(cities, null, 2), 'utf-8');

const totalLocalities = cities.reduce((s,c) => s + c.localities.length, 0);
console.log(`✅ cities.json written: ${cities.length} cities, ${totalLocalities} localities`);
console.log(`   File size: ${(fs.statSync(outPath).size / 1024).toFixed(1)} KB`);
