// Service data used across the app
export const SERVICES = [
  {
    id: 'part-time',
    name: 'Part-Time Buddy',
    shortName: 'Cleaning',
    icon: '🧹',
    color: '#E8F5F6',
    image: '/images/part-time.jpg',
    price: '₹5,000/mo',
    description: 'Flexible daily help for 4-12 hours. Ideal for working professionals needing daily cleaning, laundry, and kitchen management.',
    features: [
      { title: 'Flexible Hours', desc: 'Choose 4 to 12 hours daily' },
      { title: 'Multi-Tasking', desc: 'Cleaning, laundry, dishwashing, mopping' },
      { title: 'Background Verified', desc: 'Aadhaar & reference checked' },
      { title: 'Replacement Guarantee', desc: 'Free replacement if unsatisfied' },
    ],
  },
  {
    id: 'full-time',
    name: 'Full-Time Live-In',
    shortName: 'Live-In',
    icon: '🏠',
    color: '#FFF3E0',
    image: '/images/full-time.jpg',
    price: '₹12,000/mo',
    description: 'Complete 24x7 household management. A dedicated professional who stays with your family for ultimate convenience.',
    features: [
      { title: '24/7 Availability', desc: 'Lives with your family full-time' },
      { title: 'Complete Management', desc: 'Cooking, cleaning, laundry, everything' },
      { title: 'Police Verified', desc: 'Full background & police check' },
      { title: 'Dedicated Support', desc: 'Account manager for any issues' },
    ],
  },
  {
    id: 'elderly-care',
    name: 'Elderly Care',
    shortName: 'Elder Care',
    icon: '❤️',
    color: '#FDE8E8',
    image: '/images/eldercare.jpg',
    price: '₹14,000/mo',
    description: 'Compassionate, patient companions trained for senior needs — mobility support, medication reminders, and loving care.',
    features: [
      { title: 'Trained Caregivers', desc: 'Specialized in elderly needs' },
      { title: 'Medication Reminders', desc: 'Timely medicine management' },
      { title: 'Mobility Support', desc: 'Help with walking & daily activities' },
      { title: 'Companionship', desc: 'Emotional support & engagement' },
    ],
  },
  {
    id: 'cook',
    name: 'Specialized Cook',
    shortName: 'Cook',
    icon: '👨‍🍳',
    color: '#E8F5E9',
    image: '/images/cook.jpg',
    price: '₹8,000/mo',
    description: 'Expert chefs for North Indian, South Indian, or Continental cuisine. Hygienic, healthy, and tailored to your dietary needs.',
    features: [
      { title: 'Multi-Cuisine', desc: 'North, South Indian, Continental & more' },
      { title: 'Diet Conscious', desc: 'Follows your dietary requirements' },
      { title: 'Hygiene Trained', desc: 'Certified in food safety practices' },
      { title: 'Meal Planning', desc: 'Weekly menu planning support' },
    ],
  },
  {
    id: 'nanny',
    name: 'Babysitting & Nanny',
    shortName: 'Nanny',
    icon: '👶',
    color: '#EDE7F6',
    image: '/images/nanny.jpg',
    price: '₹10,000/mo',
    description: 'Verified, loving caretakers who engage your children safely. Focus on nutrition, hygiene, and developmental activities.',
    features: [
      { title: 'Child Development', desc: 'Age-appropriate activities & learning' },
      { title: 'Safety First', desc: 'First-aid trained caregivers' },
      { title: 'Nutrition Focus', desc: 'Healthy meal preparation for kids' },
      { title: 'Trusted & Verified', desc: 'Extensive background checks' },
    ],
  },
  {
    id: 'postnatal',
    name: 'Postnatal Care',
    shortName: 'Postnatal',
    icon: '🤱',
    color: '#FCE4EC',
    image: '/images/postnatal.jpg',
    price: 'Premium',
    description: 'Premium care inspired by global standards. Specialized infant handling, mother wellness, and holistic postpartum recovery.',
    features: [
      { title: 'Newborn Care', desc: 'Specialized infant handling & bathing' },
      { title: 'Mother Recovery', desc: 'Postpartum wellness support' },
      { title: 'Night Support', desc: 'Overnight feeding & care assistance' },
      { title: 'Expert Training', desc: 'Hospital-grade care standards' },
    ],
  },
];

export const PLAN_DETAILS = {
  silver: {
    name: 'Silver',
    price: 2499,
    pricePaise: 249900,
    duration: 90,
    replacementsTotal: 1,
    profiles: 1,
    color: '#94A3B8',
    gradient: 'linear-gradient(135deg, #94A3B8, #CBD5E1)',
    emoji: '🥈',
    popular: false,
    benefits: [
      '90-day replacement guarantee',
      '1 verified profile',
      'Basic background verification',
    ],
  },
  gold: {
    name: 'Gold',
    price: 3999,
    pricePaise: 399900,
    duration: 180,
    replacementsTotal: 3,
    profiles: 3,
    color: '#F59E0B',
    gradient: 'linear-gradient(135deg, #F59E0B, #FBBF24)',
    emoji: '🥇',
    popular: true,
    benefits: [
      '180-day replacement guarantee',
      '3 verified profiles',
      'Enhanced background checks',
      'Dedicated relationship manager',
    ],
  },
  diamond: {
    name: 'Diamond',
    price: 5999,
    pricePaise: 599900,
    duration: 365,
    replacementsTotal: 5,
    profiles: 5,
    color: '#3B82F6',
    gradient: 'linear-gradient(135deg, #3B82F6, #60A5FA)',
    emoji: '💎',
    popular: false,
    benefits: [
      '365-day replacement guarantee',
      '5 verified profiles',
      'Police verification',
      '24-hour deployment',
    ],
  },
  platinum: {
    name: 'Platinum',
    price: 8999,
    pricePaise: 899900,
    duration: 456,
    replacementsTotal: 15,
    profiles: 15,
    color: '#8B5CF6',
    gradient: 'linear-gradient(135deg, #8B5CF6, #A78BFA)',
    emoji: '👑',
    popular: false,
    benefits: [
      '456-day replacement guarantee',
      '15 free replacements',
      'VIP concierge service',
      'Police + medical verification',
      'Same-day emergency deployment',
    ],
  },
};

export const RZP_KEY = import.meta.env.VITE_RZP_KEY || '';

// All 28 States + 8 Union Territories of India (alphabetical)
export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];
