// scripts/seo/port-blog.ts — one-off importer: extracts the legacy blog/guide posts from
// the static site into data/blog/posts.ts so the content survives the cutover at the same
// (or a 301-mapped) URL. Content is preserved verbatim; only the wrapper chrome, the
// legacy CTA blocks and the .html links are rewritten.
// Run: npx tsx scripts/seo/port-blog.ts
import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = process.cwd();
const LEGACY = path.resolve(ROOT, '..', 'mybuddymaid');

interface Post {
  slug: string;
  title: string;
  description: string;
  excerpt: string;
  datePublished: string;
  dateModified: string;
  readingMinutes: number;
  category: string;
  html: string;
}

const pick = (re: RegExp, s: string, i = 1) => (s.match(re)?.[i] ?? '').trim();
const decode = (s: string) =>
  s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, ' ');

function extract(file: string, slug: string): Post | null {
  const raw = fs.readFileSync(file, 'utf8');
  // legacy blog posts use .blog-article; the comparison/guide singles use .seo-article
  const article =
    pick(/<article class="blog-article">([\s\S]*?)<\/article>/, raw) ||
    pick(/<article class="seo-article">([\s\S]*?)<\/article>/, raw);
  if (!article) return null;

  const title = decode(pick(/<h1>([\s\S]*?)<\/h1>/, raw).replace(/<[^>]+>/g, ''));
  const description = decode(pick(/<meta name="description" content="([^"]*)"/, raw));
  const ld = pick(/"datePublished":"([\d-]+)"/, raw) || pick(/📅\s*([\d-]+)/, raw);
  const modified = pick(/"dateModified":"([\d-]+)"/, raw) || ld;
  const minutes = Number(pick(/⏱️\s*(\d+)\s*min/, raw)) || 6;
  const category = decode(pick(/<div class="badge">([\s\S]*?)<\/div>/, raw).replace(/<[^>]+>/g, '')) || 'Guide';

  let html = article
    // drop the legacy CTA blocks (they point at the old app routes)
    .replace(/<div class="blog-cta">[\s\S]*?<\/div>/g, '')
    // drop the legacy related-link grids; the new template renders its own
    .replace(/<h2>Related<\/h2>\s*<div class="seo-link-grid">[\s\S]*?<\/div>/g, '')
    .replace(/<div class="seo-link-grid">[\s\S]*?<\/div>/g, '')
    // rewrite every surviving internal link to its clean URL (absolute or relative)
    .replace(/href="[^"]*index\.html#blog"/g, 'href="/blog"')
    .replace(/href="([^"]*?)\.html#([^"]*)"/g, 'href="/$1#$2"')
    .replace(/href="(\/?)blog\/index\.html"/g, 'href="/blog"')
    .replace(/href="(\/?)index\.html"/g, 'href="/"')
    .replace(/href="\/blog\.html"/g, 'href="/blog"')
    .replace(/href="blog\.html"/g, 'href="/blog"')
    .replace(/href="\/([^":]*?)\.html"/g, 'href="/$1"')
    .replace(/href="(?!https?:|mailto:|tel:|#|\/)([^":]*?)\.html"/g, 'href="/$1"')
    // the booking app moved from /home to /app
    .replace(/href="\/home"/g, 'href="/app"')
    .replace(/href="\/(auth|splash|onboarding|bookings|profile)"/g, 'href="/app/$1"')
    .trim();

  const firstPara = decode(pick(/<p>([\s\S]*?)<\/p>/, html).replace(/<[^>]+>/g, ''));
  return {
    slug,
    title,
    description: description || firstPara.slice(0, 155),
    excerpt: firstPara.slice(0, 200),
    datePublished: ld || '2026-01-01',
    dateModified: modified || ld || '2026-01-01',
    readingMinutes: minutes,
    category,
    html,
  };
}

const posts: Post[] = [];
for (const f of fs.readdirSync(path.join(LEGACY, 'blog')).filter((x) => x.endsWith('.html'))) {
  const p = extract(path.join(LEGACY, 'blog', f), f.replace(/\.html$/, ''));
  if (p) posts.push(p);
}
// flat legacy blog-*.html and the comparison/guide singles
for (const f of fs.readdirSync(LEGACY).filter((x) => x.endsWith('.html'))) {
  const name = f.replace(/\.html$/, '');
  const isFlatBlog = name.startsWith('blog-') && name !== 'blog';
  const isGuide = [
    'verified-vs-unverified-maid',
    'part-time-vs-full-time-maid',
    'nanny-vs-daycare-india',
    'maid-vs-cook-which-to-hire',
    'how-to-verify-maid-background-india',
    'home-help-hiring-checklist-india',
    'elderly-care-home-vs-caregiver',
  ].includes(name);
  if (!isFlatBlog && !isGuide) continue;
  const slug = isFlatBlog ? name.replace(/^blog-/, '') : name;
  const p = extract(path.join(LEGACY, f), slug);
  if (p) posts.push(p);
}

posts.sort((a, b) => b.datePublished.localeCompare(a.datePublished));

const out = `// GENERATED by scripts/seo/port-blog.ts from the legacy static site — content preserved.
// Re-run the script to re-import; edit posts here afterwards.
export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  excerpt: string;
  datePublished: string;
  dateModified: string;
  readingMinutes: number;
  category: string;
  html: string;
}

export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};

export const BLOG_BY_SLUG = new Map(BLOG_POSTS.map((p) => [p.slug, p]));
`;
fs.mkdirSync(path.join(ROOT, 'data', 'blog'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'data', 'blog', 'posts.ts'), out);
console.log(`port-blog: imported ${posts.length} posts -> data/blog/posts.ts`);
